/* tslint:disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const Bundesland = {
    BadenWrttemberg: 'Baden-Württemberg',
    Bayern: 'Bayern',
    Berlin: 'Berlin',
    Brandenburg: 'Brandenburg',
    Bremen: 'Bremen',
    Hamburg: 'Hamburg',
    Hessen: 'Hessen',
    Niedersachsen: 'Niedersachsen',
    MecklenburgVorpommern: 'Mecklenburg-Vorpommern',
    NordrheinWestfalen: 'Nordrhein-Westfalen',
    RheinlandPfalz: 'Rheinland-Pfalz',
    Saarland: 'Saarland',
    Sachsen: 'Sachsen',
    SachsenAnhalt: 'Sachsen-Anhalt',
    SchleswigHolstein: 'Schleswig-Holstein',
    Thringen: 'Thüringen'
} as const;

export type Bundesland = typeof Bundesland[keyof typeof Bundesland];



